/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import control.Funcoes;
import dal.ModConnect.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import static jdk.nashorn.internal.objects.Global.getDate;

/**
 *
 * @author Maria Pysklevicz
 */
public class UiCadFuncTeste extends javax.swing.JInternalFrame {

    /**
     * Creates new form UiCadFuncTeste
     */
    public UiCadFuncTeste() {
        initComponents();
        Connection con = dal.ModConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        lbl_lastNameRoman = new javax.swing.JLabel();
        lbl_nameRoman = new javax.swing.JLabel();
        lbl_lastNameKata = new javax.swing.JLabel();
        lbl_nameKata = new javax.swing.JLabel();
        lbl_lastNameKanji = new javax.swing.JLabel();
        lbl_nameKanji = new javax.swing.JLabel();
        fld_lastNameRoman = new javax.swing.JTextField();
        fld_nameRoman = new javax.swing.JTextField();
        fld_lastNameKata = new javax.swing.JTextField();
        fld_nameKata = new javax.swing.JTextField();
        fld_lastNameKanji = new javax.swing.JTextField();
        fld_nameKanji = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lbl_genre = new javax.swing.JLabel();
        lbl_dataNasc = new javax.swing.JLabel();
        lbl_nacio = new javax.swing.JLabel();
        cb_genre = new javax.swing.JComboBox<>();
        cb_nacio = new javax.swing.JComboBox<>();
        lbl_civil = new javax.swing.JLabel();
        cb_civil = new javax.swing.JComboBox<>();
        dc_dateBirth = new com.toedter.calendar.JDateChooser();
        btn_inserir = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Cadastro de Funcionários");

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_lastNameRoman.setLabelFor(fld_lastNameRoman);
        lbl_lastNameRoman.setText("Sobrenome");

        lbl_nameRoman.setLabelFor(fld_nameRoman);
        lbl_nameRoman.setText("Nome");

        lbl_lastNameKata.setLabelFor(fld_lastNameKata);
        lbl_lastNameKata.setText("Sobrenome Kana");

        lbl_nameKata.setLabelFor(fld_nameKata);
        lbl_nameKata.setText("Nome Kana");

        lbl_lastNameKanji.setLabelFor(fld_lastNameKanji);
        lbl_lastNameKanji.setText("Sobrenome Kanji");

        lbl_nameKanji.setLabelFor(fld_nameKanji);
        lbl_nameKanji.setText("Nome Kanji");

        fld_lastNameRoman.setToolTipText("<html>\n<style>\np{\nbackground-color:rgba(0,0,0,0.5);\ncolor:rgba(255,255,255,1.00);\n}\n</style>\n<p><strong>Sobrenome:</strong><br>\nEx: João Paulo Souza Silva<br>\nInserir \"Souza Silva\"</p>\n</html>");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Nome");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_nameKanji)
                            .addComponent(lbl_lastNameKanji)
                            .addComponent(lbl_nameKata)
                            .addComponent(lbl_lastNameKata)
                            .addComponent(lbl_nameRoman)
                            .addComponent(lbl_lastNameRoman))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fld_nameRoman, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(fld_lastNameKata, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fld_nameKata, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fld_lastNameKanji, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fld_nameKanji, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fld_lastNameRoman)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lastNameRoman)
                    .addComponent(fld_lastNameRoman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nameRoman)
                    .addComponent(fld_nameRoman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lastNameKata)
                    .addComponent(fld_lastNameKata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nameKata)
                    .addComponent(fld_nameKata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_lastNameKanji)
                    .addComponent(fld_lastNameKanji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nameKanji)
                    .addComponent(fld_nameKanji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbl_genre.setText("Sexo");

        lbl_dataNasc.setText("Data de nascimento");

        lbl_nacio.setLabelFor(cb_nacio);
        lbl_nacio.setText("Nacionalidade");

        cb_genre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        cb_nacio.setModel(new javax.swing.DefaultComboBoxModel(Funcoes.paises()));
        cb_nacio.setEnabled(false);

        lbl_civil.setText("Estado Cívil");

        cb_civil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Solteiro(a)", "Casado(a)" }));

        dc_dateBirth.setDateFormatString("yyyy-MM-dd");
        dc_dateBirth.setIcon(null);
        dc_dateBirth.setMaxSelectableDate(new java.util.Date(253370736076000L));
        dc_dateBirth.setMinSelectableDate(new java.util.Date(-2209017524000L));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_dataNasc)
                            .addComponent(lbl_civil)
                            .addComponent(lbl_nacio)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(lbl_genre)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(cb_genre, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_civil, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_nacio, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dc_dateBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(149, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_dataNasc)
                    .addComponent(dc_dateBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_genre)
                    .addComponent(cb_genre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_civil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_civil))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_nacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_nacio))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        btn_inserir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_inserir.setText("Salvar");
        btn_inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btn_inserir, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inserirActionPerformed
        // TODO add your handling code here:
        addPessoa();
        
    }//GEN-LAST:event_btn_inserirActionPerformed
    private void addPessoa(){
        Connection con = dal.ModConnect.connect();
        String sql = "INSERT INTO people (last_name, first_name, last_furi,first_furi,last_kanji,first_kanji,date_birth,gender,civil_status) VALUES (?,?,?,?,?,?,?,?,?);";
         try{
             
            PreparedStatement pst = con.prepareStatement(sql);
            pst =con.prepareStatement(sql);
            pst.setString(1,fld_lastNameRoman.getText());
            pst.setString(2,fld_nameRoman.getText());
            pst.setString(3,fld_lastNameKata.getText());
            pst.setString(4,fld_nameKata.getText());
            pst.setString(5,fld_lastNameKanji.getText());
            pst.setString(6,fld_nameKanji.getText());
        
            //datechooser
            java.util.Date date = dc_dateBirth.getDate();           
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            //java.util.Date dateStr = format.parse(date);
            java.sql.Date dateDB = new java.sql.Date(date.getTime());
            pst.setDate(7,dateDB);        
            //comboBox
            pst.setString(8,cb_genre.getSelectedItem().toString());
            pst.setInt(9,cb_civil.getSelectedIndex());
            /*--------------------------------------------------------
            VALIDAÇÃO DE CAMPOS
            ----------------------------------------------------------*/
            /*if(nomedocampo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Campo obrigatorio");
            }else{*/
            //atualiza a tabela
            //confirma inserção de dados
            int adic = pst.executeUpdate();
            if(adic != 0){
                JOptionPane.showMessageDialog(null,"Func add com sucesso");
                //nomedocampo.setText(null);
                //nomedocombobox.setSelectedItem(null);
            }
        //}
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
             System.out.println(e);
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inserir;
    public static javax.swing.JComboBox<String> cb_civil;
    private javax.swing.JComboBox<String> cb_genre;
    private javax.swing.JComboBox<String> cb_nacio;
    private com.toedter.calendar.JDateChooser dc_dateBirth;
    private javax.swing.JTextField fld_lastNameKanji;
    private javax.swing.JTextField fld_lastNameKata;
    private javax.swing.JTextField fld_lastNameRoman;
    private javax.swing.JTextField fld_nameKanji;
    private javax.swing.JTextField fld_nameKata;
    private javax.swing.JTextField fld_nameRoman;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel lbl_civil;
    private javax.swing.JLabel lbl_dataNasc;
    private javax.swing.JLabel lbl_genre;
    private javax.swing.JLabel lbl_lastNameKanji;
    private javax.swing.JLabel lbl_lastNameKata;
    private javax.swing.JLabel lbl_lastNameRoman;
    private javax.swing.JLabel lbl_nacio;
    private javax.swing.JLabel lbl_nameKanji;
    private javax.swing.JLabel lbl_nameKata;
    private javax.swing.JLabel lbl_nameRoman;
    // End of variables declaration//GEN-END:variables
}
