/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Maria Pysklevicz
 */
public class UiFuncSearch extends javax.swing.JInternalFrame {
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form UiFuncSearch
     */
    public UiFuncSearch() {
        initComponents();
        con = dal.ModConnect.connect();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_funcSearch_res = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        fld_funcSearch = new javax.swing.JTextField();
        btn_funcSearch = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Pesquisar Funcionário");

        tbl_funcSearch_res.setAutoCreateRowSorter(true);
        tbl_funcSearch_res.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        tbl_funcSearch_res.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Sobrenome", "Nome", "Furigana", "FuriNome", "Kanji", "KanjiNome", "Nasc", "sexo", "civilStatus"
            }
        ));
        tbl_funcSearch_res.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(tbl_funcSearch_res);
        tbl_funcSearch_res.getAccessibleContext().setAccessibleName("");

        jLabel1.setText("Pesquisar por Nome");

        fld_funcSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fld_funcSearchKeyReleased(evt);
            }
        });

        btn_funcSearch.setText("Pesquisar");
        btn_funcSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_funcSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fld_funcSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_funcSearch)
                .addContainerGap(229, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fld_funcSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_funcSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("Pesquisar Funcionario");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_funcSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_funcSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_funcSearchActionPerformed

    private void fld_funcSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fld_funcSearchKeyReleased
        // TODO add your handling code here:
        pesq_func();
    }//GEN-LAST:event_fld_funcSearchKeyReleased
    
    private void pesq_func(){
        
        String sql="SELECT last_name as Sobrenome, first_name as Nome, last_furi as Furigana,first_furi as FuriNome, last_kanji as Kanji, first_kanji as KanjiNome, date_birth as Nasc, gender as sexo, civil_status as civilStatus FROM people where last_name like ?";
        try{
            pst = con.prepareStatement(sql);
            
            //passando o conteudo da pesquisa para ?
            pst.setString(1,fld_funcSearch.getText() + "%");
            rs = pst.executeQuery();
            // utilizando biblioteca rs2xml.jar para tabela UI 
            tbl_funcSearch_res.setModel(DbUtils.resultSetToTableModel(rs));   
    
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,e);
            System.out.println(e);
        }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_funcSearch;
    private javax.swing.JTextField fld_funcSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_funcSearch_res;
    // End of variables declaration//GEN-END:variables
}
