
package ui;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Maria Pysklevicz
 */
public class UiPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form UIPrincipal
     */
    public UiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        lbl_user = new javax.swing.JLabel();
        lbl_data = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        mb_cad = new javax.swing.JMenu();
        mb_cad_func = new javax.swing.JMenuItem();
        mb_cad_user = new javax.swing.JMenuItem();
        mb_cad_dep = new javax.swing.JMenuItem();
        mb_cad_emp = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mb_funcSearch = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        mb_rel = new javax.swing.JMenu();
        mb_rel_ent = new javax.swing.JMenuItem();
        mb_help = new javax.swing.JMenu();
        mb_help_about = new javax.swing.JMenuItem();
        mb_op = new javax.swing.JMenu();
        mb_op_exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Wicz HR Manager");
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1200, 800));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setBackground(new java.awt.Color(102, 102, 102));
        desktop.setAutoscrolls(true);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 699, Short.MAX_VALUE)
        );

        lbl_user.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_user.setText("Usuário");

        lbl_data.setText("Data");

        mb_cad.setText("Cadastro");
        mb_cad.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mb_cad_func.setText("Funcionário");
        mb_cad_func.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_cad_funcActionPerformed(evt);
            }
        });
        mb_cad.add(mb_cad_func);

        mb_cad_user.setText("Usuário");
        mb_cad_user.setEnabled(false);
        mb_cad_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_cad_userActionPerformed(evt);
            }
        });
        mb_cad.add(mb_cad_user);

        mb_cad_dep.setText("Dependentes");
        mb_cad_dep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_cad_depActionPerformed(evt);
            }
        });
        mb_cad.add(mb_cad_dep);

        mb_cad_emp.setText("Empresa");
        mb_cad_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mb_cad_empMouseClicked(evt);
            }
        });

        jMenu1.setText("Departamento");

        jMenuItem2.setText("Setor");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Seção");
        jMenu1.add(jMenuItem3);

        mb_cad_emp.add(jMenu1);

        mb_cad.add(mb_cad_emp);

        menuBar.add(mb_cad);

        jMenu2.setText("Pesquisar");

        mb_funcSearch.setText("Funcionário");
        mb_funcSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_funcSearchActionPerformed(evt);
            }
        });
        jMenu2.add(mb_funcSearch);

        jMenuItem4.setText("Empresa");
        jMenu2.add(jMenuItem4);

        menuBar.add(jMenu2);

        mb_rel.setText("Relatorio");
        mb_rel.setEnabled(false);

        mb_rel_ent.setText("Por Empresa");
        mb_rel.add(mb_rel_ent);

        menuBar.add(mb_rel);

        mb_help.setText("Ajuda");

        mb_help_about.setText("Sobre");
        mb_help_about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_help_aboutActionPerformed(evt);
            }
        });
        mb_help.add(mb_help_about);

        menuBar.add(mb_help);

        mb_op.setText("Opções");

        mb_op_exit.setText("Sair");
        mb_op_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mb_op_exitActionPerformed(evt);
            }
        });
        mb_op.add(mb_op_exit);

        menuBar.add(mb_op);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(desktop)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 1026, Short.MAX_VALUE)
                        .addComponent(lbl_user)
                        .addGap(79, 79, 79)
                        .addComponent(lbl_data)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_user)
                    .addComponent(lbl_data))
                .addGap(18, 18, 18)
                .addComponent(desktop)
                .addGap(33, 33, 33))
        );

        setSize(new java.awt.Dimension(1216, 839));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Date data = new Date();
        //DateFormat formatar;
        //formatar = DateFormat.getDateInstance(DateFormat.DEFAULT);
        SimpleDateFormat formatar = new SimpleDateFormat("yyyy/MM/dd");
        lbl_data.setText(formatar.format(data));
        //lbl_user.setText(text);
        
        
    }//GEN-LAST:event_formWindowActivated

    private void mb_op_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_op_exitActionPerformed
        // TODO add your handling code here:
        //caixa de dialogo
        int sair = JOptionPane.showConfirmDialog(null, "Tem Certeza que deseja sair?", "   Atenção", JOptionPane.YES_NO_OPTION);
        if(sair ==JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_mb_op_exitActionPerformed

    private void mb_help_aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_help_aboutActionPerformed
        // TODO add your handling code here:
        //tela sobre
        UiAbout about = new UiAbout();
        about.setVisible(true);
    }//GEN-LAST:event_mb_help_aboutActionPerformed

    private void mb_cad_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_cad_userActionPerformed
        // TODO add your handling code here:
        //chama tela usuario
        UiCadUsuario usuario =new UiCadUsuario();
        usuario.setVisible(true);
        desktop.add(usuario);
        
    }//GEN-LAST:event_mb_cad_userActionPerformed

    private void mb_cad_funcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_cad_funcActionPerformed
        // TODO add your handling code here:
        //chama tela funcionarios
        UiCadFuncTeste func = new UiCadFuncTeste();
        func.setVisible(true);
        desktop.add(func);
        
    }//GEN-LAST:event_mb_cad_funcActionPerformed

    private void mb_cad_depActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_cad_depActionPerformed
        // TODO add your handling code here:
        UiCadDependentes depen = new UiCadDependentes();
        depen.setVisible(true);
        desktop.add(depen);
    }//GEN-LAST:event_mb_cad_depActionPerformed

    private void mb_cad_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mb_cad_empMouseClicked
        // TODO add your handling code here:
        UiCadEmp emp = new UiCadEmp();
        emp.setVisible(true);
        desktop.add(emp);
    }//GEN-LAST:event_mb_cad_empMouseClicked

    private void mb_funcSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mb_funcSearchActionPerformed
        // TODO add your handling code here:
        UiFuncSearch funcSearch = new UiFuncSearch();
        funcSearch.setVisible(true);
        desktop.add(funcSearch);
    }//GEN-LAST:event_mb_funcSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JLabel lbl_data;
    public static javax.swing.JLabel lbl_user;
    private javax.swing.JMenu mb_cad;
    private javax.swing.JMenuItem mb_cad_dep;
    private javax.swing.JMenu mb_cad_emp;
    private javax.swing.JMenuItem mb_cad_func;
    public static javax.swing.JMenuItem mb_cad_user;
    private javax.swing.JMenuItem mb_funcSearch;
    private javax.swing.JMenu mb_help;
    private javax.swing.JMenuItem mb_help_about;
    private javax.swing.JMenu mb_op;
    private javax.swing.JMenuItem mb_op_exit;
    public static javax.swing.JMenu mb_rel;
    private javax.swing.JMenuItem mb_rel_ent;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables
}
